class Layouy_padrao:

    def __init__(self):
        self.colunas_essencias = ['Origem nota fiscal',
                             'Filial',
                             'Tributação',
                             'Número do documento',
                             'Data Vencimento Documento',
                             'Número nota',
                             'Item Fatura',
                             'CFOP',
                             'Data emissão Sefaz',
                             'Data emissão Atacadão',
                             'Data efetivação',
                             'Data posto fiscal',
                             'CNPJ',
                             'Razão social',
                             'Mercadoria',
                             'Descrição Mercadoria',
                             'alq_org',
                             'alq_des',
                             'Valor total nota sefaz',
                             'Valor IPI sefaz',
                             'Valor base calculo sefaz',
                             'Valor ICMS substituto sefaz',
                             'Valor ICMS antecipado sefaz',
                             'Valor ICMS diferencial sefaz',
                             'Valor icms sefaz',
                             'Valor total nota atacadão',
                             'Valor IPI atacadão',
                             'Valor base calculo atacadão',
                             'Valor icms atacadao',
                             'Crédito Antecip',
                             'Cred ICMS Retido(layout)',
                             'Valor divergência',
                             'Valor total base de calculo substituto',
                             'Valor total ICMS substituto',
                             'Código Receita',
                             'UF',
                             'Nota Devolução',
                             'Valor Total Nf Dev.',
                             'Valor Base. Calc. subst. Nf Dev.',
                             'Valor total ICMS substituto Nf Dev.',
                             'Cobrado Anteriormente no Documento']